console.log("como hacer una torta");
console.log("paso1, prender el horno");
console.log("paso2, batir el azucar, los huevos, la esencia de vainilla");
console.log("paso3, agregar leche");
console.log("paso4, agregar harina");
console.log("paso5, poner en el molde");
console.log("paso6, llevar al horno 100°");
console.log("paso7, retirar del horno a los 30 min");
console.log("paso8, espolvorear azucar impalpable");
console.log("paso9, cortar");
console.log("paso10, comer");
